version: '3.8'

services:
  database:
    image: redis:latest
    container_name: memoa-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - redis-network

  app:
    image: ${DOCKER_USERNAME}/memoa-server-app:latest
    ports:
      - "8080:8080"
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      ACCESS_END: ${ACCESS_END}
      REFRESH_END: ${REFRESH_END}
      JWT_KEY: ${JWT_KEY}
    restart: always
    networks:
      - redis-network

networks:
  redis-network:
