version: '3.8'

services:
  database:
    image: redis:latest
    container_name: memoa-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my-network
  app:
    image: memoa-server-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}

      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}

      ACCESS_END: ${ACCESS_END}
      REFRESH_END: ${REFRESH_END}
      JWT_KEY: ${JWT_KEY}
    restart: always
    networks:
      - my-network

networks:
  my-network:
