version: '3.8'

services:
  redis:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - redis-data:/data
    restart: on-failure

  springboot:
    image: ${DOCKER_USERNAME}/memoa-server-app:latest
    container_name: memoa_server
    ports:
      - "80:8080"
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: 6379
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      ACCESS_END: ${ACCESS_END}
      REFRESH_END: ${REFRESH_END}
      JWT_KEY: ${JWT_KEY}
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      SPRING_REDIS_HOST: ${REDIS_HOST}
    restart: always
volumes:
  redis-data: