spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USER}
        password: ${MAIL_PASSWORD}
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true

    application:
        name: memoa-server
    data:
        redis:
            host: ${REDIS_HOST}
            password: ${REDIS_PASSWORD}
            port: ${REDIS_PORT}
    datasource:
        password: ${MYSQL_PASSWORD}
        url: ${MYSQL_HOST}
        username: ${MYSQL_USER}
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    jwt:
        access:
            expiration: ${ACCESS_END}
        refresh:
            expiration: ${REFRESH_END}
        secret: ${JWT_KEY}

springdoc:
    api-docs:
        enabled: true
        version: openapi_3_0
        path: /v3/api-docs
    default-consumes-media-type: application/json
    auto-tag-classes: true
    swagger-ui:
        operationsSorter: method
        path: /swagger-ui.html