spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USER}
        password: ${MAIL_PASSWORD}
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true

    application:
        name: memoa-server
    data:
        mongodb:
            uri: imsi # 임시 데이터 후에 추가 필요
            username: imsi
            password: imsi
        redis:
            host: ${REDIS_HOST}
            password: ${REDIS_PASSWORD}
            port: ${REDIS_PORT}
    datasource:
        password: ${MYSQL_PASSWORD}
        url: ${MYSQL_HOST}
        username: ${MYSQL_USER}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    jwt:
        access:
            expiration: ${ACCESS_END}
        refresh:
            expiration: ${REFRESH_END}
        secret: ${JWT_KEY}