name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  ACCESS_END: ${{ secrets.ACCESS_END }}
  REFRESH_END: ${{ secrets.REFRESH_END }}
  JWT_KEY: ${{ secrets.JWT_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: set chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t memoa-server-app:latest .
          docker tag memoa-server-app:latest ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DOCKER_USERNAME, MAIL_USER, MAIL_PASSWORD, REDIS_HOST, REDIS_PASSWORD, REDIS_PORT, MYSQL_PASSWORD, MYSQL_HOST, MYSQL_USER, ACCESS_END, REFRESH_END, JWT_KEY
          script: |
            cd .
            
            docker stop memoa-server
            docker rm memoa-server
            docker rmi ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest
            
            echo "DOCKER_USERNAME=$DOCKER_USERNAME" > .env
            echo "MAIL_USER=$MAIL_USER" >> .env
            echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env
            echo "REDIS_HOST=$REDIS_HOST" >> .env
            echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> .env
            echo "REDIS_PORT=$REDIS_PORT" >> .env
            echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
            echo "MYSQL_HOST=$MYSQL_HOST" >> .env
            echo "MYSQL_USER=$MYSQL_USER" >> .env
            echo "ACCESS_END=$ACCESS_END" >> .env
            echo "REFRESH_END=$REFRESH_END" >> .env
            echo "JWT_KEY=$JWT_KEY" >> .env
            
            docker run -d -p 80:80 --network="host" --env-file .env --name memoa-server ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest
#
#            docker pull $DOCKER_USERNAME/memoa-server-app:latest
#
#
#            docker-compose down
#            docker-compose --env-file .env up -d
