name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: set chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t memoa-server-app:latest .
          docker tag memoa-server-app:latest ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd .
            docker pull ${{ secrets.DOCKER_USERNAME }}/memoa-server-app:latest

            export MAIL_USER=${{ secrets.MAIL_USER }}
            export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            export MYSQL_USER=${{ secrets.MYSQL_USER }}
            export ACCESS_END=${{ secrets.ACCESS_END }}
            export REFRESH_END=${{ secrets.REFRESH_END }}
            export JWT_KEY=${{ secrets.JWT_KEY }}

            docker-compose down
            docker-compose up -d
